# Supabase Local Development Configuration

[api]
# Port to use for the API server. Default is 54321.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API routes.
# Others schemas will be private, but accessible via the internal query route.
schemas = ["public", "storage", "graphql_public"]
# Default number of rows returned when limit is not specified
max_rows = 1000

[db]
# Port to use for the local database. Default is 54322.
port = 54322
# The database major version to use. This has to be the same as the environment variable `POSTGRES_MAJOR_VERSION` accepted by the official PostgreSQL docker image.
major_version = 17

[studio]
# Port to use for Supabase Studio. Default is 54323.
port = 54323

[inbucket]
# Port to use for the email testing server web interface. Default is 54324.
port = 54324
# Port to use for the email testing server SMTP inbox. Default is 54325.
smtp_port = 54325

[storage]
# The max file size allowed (in bytes). Default is 52428800 (50MB)
file_size_limit = 52428800

[auth]
# The default JWT expiry is set to 3600 seconds (1 hour)
jwt_expiry = 3600
